name: hbase
description: "huocool based sub sys app base"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: http://localhost:4000/ # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1+11

environment:
  sdk: ^3.5.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter    

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  quiver: ^3.2.2
  get: ^4.6.6
  shared_preferences: ^2.2.3
  flutter_staggered_grid_view: ^0.7.0
  # 将 infinite_scroll_pagination 的版本固定为 4.0.0 避免出现如下的错误；（背景：在构建 swapface_base_app 的时候因为 infinite_scroll_pagination 升级为 4.1.0 后出现如下错误）
  # RenderViewport does not support returning intrinsic dimensions.
  # Calculating the intrinsic dimensions would require instantiating every child of the viewport, which
  # defeats the point of viewports being lazy.
  # If you are merely trying to shrink-wrap the viewport in the main axis direction, consider a
  # RenderShrinkWrappingViewport render object (ShrinkWrappingViewport widget), which achieves that
  # effect without implementing the intrinsic dimension API.
  #
  # The relevant error-causing widget was:
  #  SliverFillRemaining
  #   SliverFillRemaining:file:///Users/mac/.pub-cache/hosted/pub.dev/infinite_scroll_pagination-4.1.0/lib/src/widgets/helpers/paged_layout_builder.dart:311:16
  #
  # When the exception was thrown, this was the stack:
  # #0      RenderViewportBase.debugThrowIfNotCheckingIntrinsics.<anonymous closure> (package:flutter/src/rendering/viewport.dart:491:9)
  # #1      RenderViewportBase.debugThrowIfNotCheckingIntrinsics (package:flutter/src/rendering/viewport.dart:505:6)
  # #2      RenderViewportBase.computeMaxIntrinsicHeight (package:flutter/src/rendering/viewport.dart:529:12)
  infinite_scroll_pagination: 4.0.0
  scroll_to_index: ^3.0.1
  easy_debounce: ^2.0.3  
  ionicons: ^0.2.2  
  sycomponents:
    version: ^2.1.6
    hosted:
      url: http://localhost:4000/
  appbase:
    version: ^1.0.1
    hosted:
      url: http://localhost:4000/
  sypayment:
    version: ^2.1.3
    hosted:
      url: http://localhost:4000/
  sypages:
    version: ^2.0.0
    hosted:
      url: http://localhost:4000/
  intl: ^0.19.0
  proste_indexed_stack: ^0.2.4
  community_material_icon: ^5.9.55
  # 注意版本最好与 sycomponents 中的保持一致
  visibility_detector: ^0.4.0+2
  flutter_font_icons: ^2.2.7
  format: ^1.5.2
  http: ^1.5.0
  image_picker: ^1.1.2  
  mime: ^1.0.5
  get_time_ago: ^2.3.2
  soft_edge_blur: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
