name: hyou1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.2.3
  ionicons: ^0.2.2  
  hbase: 
    path: ../../../
  appbase:
    version: ^1.0.0
    hosted:
      url: http://localhost:4000/
  proste_indexed_stack: ^0.2.4
  community_material_icon: ^5.9.55    

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - .env
    - images/
